Remove PlatformIO, replace with minimqtt alone (Fixes #4)
mechawrench/wificom-lib pull request #26
Opened 2022-11-03 00:50 UTC by mechawrench

- Removes PlatformIO dependency (saves RAM)
- Updates code.py with new minimqtt.py import and calls

2022-11-04 00:26 UTC, dmcomm requested changes

2022-11-05 05:05 UTC, mechawrench commented on lib/wificom/mqtt/minimqtt.py
> +	print('Published to {0} with PID {1}'.format(topic, pid))
Removed the on-publish callback completely, we can re-add as needed in development

2022-11-05 05:06 UTC, mechawrench commented on lib/wificom/mqtt/minimqtt.py
> +	print(time.monotonic(), "New RTB message on topic {0}: {1} ".format(topic, message))
Also removed the import time as it was unused after removing the time output

2022-11-05 17:14 UTC, dmcomm approved these changes

2022-11-05 17:15 UTC, merged